import pandas as pd
import os

input_folder = "C:\TruckIDMe Project\g80"
output_folder = "C:\TruckIDMe Project\g80_dropped"

os.makedirs(output_folder,exist_ok=True)

for filename in os.listdir(input_folder):
    input_path = os.path.join(input_folder,filename)
    print(f" Processing : {filename}")

    try:
        df = pd.read_csv(input_path)
        df.columns = df.columns.str.strip()

        columns_to_drop = [
    '3031 Aftertreatment 1 Diesel Exhaust Fluid Tank Temperature 1_std',
    '1761 Aftertreatment 1 Diesel Exhaust Fluid Tank Volume_std',
    '5466 Aftertreatment 1 Diesel Particulate Filter Soot Load Regeneration Threshold_std',
    '3721 Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration_std',

    '3242 Aftertreatment 1 Diesel Particulate Filter Intake Temperature_min',


    '171 Ambient Air Temperature_std',
    '171 Ambient Air Temperature_max',
    '171 Ambient Air Temperature_min',
    '171 Ambient Air Temperature_mean',
    '171 Ambient Air Temperature_median',


    '908 Relative Speed; Rear Axle #1, Right Wheel_max',





    '108 Barometric Pressure_std',
    '117 Brake Primary Pressure_std',
    '118 Brake Secondary Pressure_std',
    '110 Engine Coolant Temperature_std',
    '1136 Engine ECU Temperature_std',
    '412 Engine Exhaust Gas Recirculation 1 Temperature_std',
    '975 Engine Fan 1 Estimated Percent Speed_std',
    '250 Engine Total Fuel Used_std',
    '247 Engine Total Hours of Operation_std',
    '236 Engine Total Idle Fuel Used_std',
    '235 Engine Total Idle Hours_std',
    '249 Engine Total Revolutions_std',
    '182 Engine Trip Fuel_std',
    '1172 Engine Turbocharger 1 Compressor Intake Temperature_std',
    '103 Engine Turbocharger 1 Speed_std',
    '96 Fuel Level 1_std',
    '1087 Service Brake Circuit 1 Air Pressure_std',
    '1088 Service Brake Circuit 2 Air Pressure_std',
    '177 Transmission Oil Temperature 1_std',
    '1029 Trip Average Fuel Rate_std',

    '4154 Actual Engine - Percent Torque (Fractional)_min'

    '918 Trip Distance (High Resolution)_std',
    '918 Trip Distance (High Resolution)_min',
    '918 Trip Distance (High Resolution)_max',
    '918 Trip Distance (High Resolution)_mean',
    '918 Trip Distance (High Resolution)_median'

    '4816 Transmission Torque Converter Lockup Transition in Process_min',
    

    '100 Engine Oil Pressure 1_min',
    '100 Engine Oil Pressure 1_max',
    '100 Engine Oil Pressure 1_std',
    '100 Engine Oil Pressure 1_mean',
    '100 Engine Oil Pressure 1_median',

    '3544 Time Remaining in Engine Operating State_min', # this columns/aggregates are missing values acorss drivers consistently, mostly due to sampling.. hence dropping these. 
    '3544 Time Remaining in Engine Operating State_max',
    '3544 Time Remaining in Engine Operating State_mean',
    '3544 Time Remaining in Engine Operating State_std',
    '3544 Time Remaining in Engine Operating State_median'
    
    '1087 Service Brake Circuit 1 Air Pressure_max'
'1087 Service Brake Circuit 1 Air Pressure_max',
'105 Engine Intake Manifold 1 Temperature_min',
'T1_mean',
'518 Engine Requested Torque Torque Limit_mean',
'1242 Instantaneous Estimated Brake Power_max',
'101 Engine Crankcase Pressure 1_min',
'RMS_VVEL_min',
'Head_imu2_mean',
'907 Relative Speed Rear Axle 1 Left Wheel_max',
'185 Engine Average Fuel Economy_min',
'1088 Service Brake Circuit 2 Air Pressure_max',
'3246 Aftertreatment 1 Diesel Particulate Filter Outlet Temperature_mean',
'412 Engine Exhaust Gas Recirculation 1 Temperature_max',
'heading_mean',
'3246 Aftertreatment 1 Diesel Particulate Filter Outlet Temperature_min',
'IMU_Kalman_Filter_Status_mean',
'1136 Engine ECU Temperature_max',
'908 Relative Speed Rear Axle 1 Right Wheel_std',
'1242 Instantaneous Estimated Brake Power_mean',
'Roll_Angle_mean',
'412 Engine Exhaust Gas Recirculation 1 Temperature_std',
'1717 Actual Maximum Available Retarder Percent Torque_max',
'Head_imu_max',
'Exported_Radius_of_turn_min',
'91 Accelerator Pedal Position 1_max',
'236 Engine Total Idle Fuel Used_mean',
'5862 Aftertreatment 1 SCR Intermediate Temperature_max',
'5466 Aftertreatment 1 Diesel Particulate Filter Soot Load Regeneration Threshold_std',
'2945 Active Shift Console Indicator_min',
'4154 Actual Engine Percent Torque Fractional_max',
'PreKF_Heading_max',
'ADC_CH2_std',
'190 Engine Speed CAN0_std',
'latitude_max',
'105 Engine Intake Manifold 1 Temperature_std',
'907 Relative Speed Rear Axle 1 Left Wheel_mean',
'4207 Message Checksum_mean',
'Lat_Jerk_mean',
'ADC_CH3_max',
'92 Engine Percent Load At Current Speed_std',
'918 Trip Distance High Resolution_max',
'POSCov_xy_min',
'168 Battery Potential Power Input 1_mean',
'4206 Message Counter_min',
'VELCov_xz_std',
'975 Engine Fan 1 Estimated Percent Speed_min',
'4363 Aftertreatment 1 SCR Outlet Temperature_mean',
'512 Driver s Demand Engine Percent Torque_mean',
'RMS_HPOS_std',
'986 Engine Fan 1 Requested Percent Speed_std',
'vertical_velocity_kmh_min',
'3721 Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration_min',
'Lat_accel_min',
'3357 Actual Maximum Available Engine Percent Torque_mean',
'518 Engine Requested Torque Torque Limit_std',
'641 Engine Variable Geometry Turbocharger Actuator 1_max',
'RollRate_max',
'VELCov_xx_max',
'Exported_Relative_height_max',
'3231 Aftertreatment 1 Outlet Wide Range Percent Oxygen 1 Reading Stable_min',
'184 Engine Instantaneous Fuel Economy_std',
'3251 Aftertreatment 1 Diesel Particulate Filter Differential Pressure_max',
'Lat_Vel_mean',
'SlipHead_std',
'solution_type_min',
'3229 Aftertreatment 1 Outlet Gas Sensor 1 at Temperature_max',
'velocity_quality_kmh_mean',
'RMS_VVEL_std',
'VELCov_xy_std',
'3229 Aftertreatment 1 Outlet Gas Sensor 1 at Temperature_std',
'Pitch_imu_max',
'ADC_CH1_std',
'244 Trip Distance_std',
'long_max',
'gps_sats_mean',
'3216 Engine Exhaust 1 NOx 1_min',
'X_Accel_mean',
'VELCov_xz_max',
'Exported_Elapsed_time_max',
'POSCov_xy_mean',
'Roll_imu_mean',
'1717 Actual Maximum Available Retarder Percent Torque_std',
'904 Front Axle Speed_std',
'2979 Vehicle Acceleration Rate Limit Status_max',
'Y_Accel_max',
'574 Transmission Shift In Process_min',
'heading_min',
'POSCov_yz_max',
'POSCov_yz_mean',
'Pos_X_min',
'Long_accel_max',
'Head_imu_std',
'110 Engine Coolant Temperature_mean',
'247 Engine Total Hours of Operation_min',
'3544 Time Remaining in Engine Operating State_max',
'headingDegree_max',
'Exported_Lateral_acceleration_mean',
'513 Actual Engine Percent Torque_max',
'171 Ambient Air Temperature_min',
'5398 Estimated Pumping Percent Torque_std',
'YawRate_std',
'3216 Engine Exhaust 1 NOx 1_std',
'longitude_min',
'RMS_VPOS_max',
'1172 Engine Turbocharger 1 Compressor Intake Temperature_min',
'Exported_Elapsed_time_std',
'VELCov_xy_max',
'PreKF_VertSpd_mean',
'PreKF_Latitude_max',
'2978 Estimated Engine Parasitic Losses Percent Torque_max',
'177 Transmission Oil Temperature 1_mean',
'514 Nominal Friction Percent Torque_mean',
'POSCov_xx_mean',
'VELCov_yz_min',
'2432 Engine Demand Percent Torque_min',
'526 Transmission Actual Gear Ratio_mean',
'Head_imu_mean',
'glonass_sats_max',
'1029 Trip Average Fuel Rate_min',
'Lat_Vel_min',
'Slip_Angle_max',
'Yaw_Rate_std',
'POSCov_yy_mean',
'ADC_CH1_mean',
'Temp_std',
'Lat_accel_mean',
'574 Transmission Shift In Process_std',
'641 Engine Variable Geometry Turbocharger Actuator 1_std',
'POSCov_zz_std',
'526 Transmission Actual Gear Ratio_min',
'641 Engine Variable Geometry Turbocharger Actuator 1_min',
'110 Engine Coolant Temperature_min',
'182 Engine Trip Fuel_min',
'vertical_velocity_kmh_mean',
'DualStatus_std',
'161 Transmission 1 Input Shaft Speed_std',
'3239 Aftertreatment 2 Intake Dew Point_max',
'117 Brake Primary Pressure_max',
'POSCov_xz_std',
'110 Engine Coolant Temperature_std',
'RobotHead_min',
'105 Engine Intake Manifold 1 Temperature_max',
'Pitch_Ang_mean',
'3242 Aftertreatment 1 Diesel Particulate Filter Intake Temperature_mean',
'1088 Service Brake Circuit 2 Air Pressure_mean',
'512 Driver s Demand Engine Percent Torque_std',
'412 Engine Exhaust Gas Recirculation 1 Temperature_mean',
'1172 Engine Turbocharger 1 Compressor Intake Temperature_max',
'satellites_std',
'3229 Aftertreatment 1 Outlet Gas Sensor 1 at Temperature_mean',
'515 Engine s Desired Operating Speed_max',
'177 Transmission Oil Temperature 1_min',
'92 Engine Percent Load At Current Speed_min',
'108 Barometric Pressure_std',
'Lat_Jerk_std',
'lat_std',
'Exported_Distance_mean',
'118 Brake Secondary Pressure_min',
'526 Transmission Actual Gear Ratio_std',
'solution_type_max',
'108 Barometric Pressure_min',
'184 Engine Instantaneous Fuel Economy_max',
'Y_Accel_std',
'132 Engine Intake Air Mass Flow Rate_mean',
'157 Engine Fuel 1 Injector Metering Rail 1 Pressure_min',
'523 Transmission Current Gear_std',
'RMS_HPOS_mean',
'Pos_X_mean',
'906 Relative Speed Front Axle Right Wheel_min',
'Exported_Distance_min',
'PreKF_Latitude_mean',
'VELCov_yy_std',
'glonass_sats_mean',
'Pitch_imu_std',
'PreKF_Longitude_min',
'157 Engine Fuel 1 Injector Metering Rail 1 Pressure_mean',
'3230 Aftertreatment 1 Outlet NOx 1 Reading Stable_std',
'POSCov_xz_mean',
'513 Actual Engine Percent Torque_std',
'1172 Engine Turbocharger 1 Compressor Intake Temperature_std',
'117 Brake Primary Pressure_std',
'PreKF_Alt_min',
'Pos_Z_std',
'187 Power Takeoff Set Speed_max',
'PreKF_VertSpd_std',
'100 Engine Oil Pressure 1_max',
'VELCov_zz_max',
'3232 Aftertreatment 1 Outlet Gas Sensor 1 Heater Preliminary FMI_min',
'PreKF_Latitude_std',
'ADC_CH4_max',
'573 Transmission Torque Converter Lockup Engaged_mean',
'523 Transmission Current Gear_max',
'4206 Message Counter_std',
'Pitch_Ang_std',
'1209 Engine Exhaust Bank 1 Pressure 1_max',
'SlipHead_max',
'True_Head_mean',
'108 Barometric Pressure_max',
'Pos_Qual_max',
'5052 Transmission Clutch Converter Input Speed_max',
'1136 Engine ECU Temperature_std',
'132 Engine Intake Air Mass Flow Rate_std',
'247 Engine Total Hours of Operation_std',
'4765 Aftertreatment 1 Diesel Oxidation Catalyst Intake Temperature_max',
'191 Transmission 1 Output Shaft Speed_max',
'Exported_Relative_height_std',
'1209 Engine Exhaust Bank 1 Pressure 1_min',
'524 Transmission Selected Gear_mean',
'5862 Aftertreatment 1 SCR Intermediate Temperature_mean',
'Pos_Y_max',
'2659 Engine Exhaust Gas Recirculation 1 Mass Flow Rate_std',
'4207 Message Checksum_std',
'longitude_mean',
'3031 Aftertreatment 1 Diesel Exhaust Fluid Tank Temperature 1_std',
'3544 Time Remaining in Engine Operating State_mean',
'905 Relative Speed Front Axle Left Wheel_std',
'longitude_std',
'986 Engine Fan 1 Requested Percent Speed_max',
'190 Engine Speed CAN0_min',
'DualStatus_min',
'Pos_X_max',
'3241 Aftertreatment 1 Exhaust Temperature 1_max',
'ADC_CH2_max',
'904 Front Axle Speed_max',
'3239 Aftertreatment 2 Intake Dew Point_mean',
'574 Transmission Shift In Process_mean',
'Lat_Vel_max',
'PreKF_Alt_mean',
'92 Engine Percent Load At Current Speed_mean',
'177 Transmission Oil Temperature 1_max',
'3610 Aftertreatment 1 Diesel Particulate Filter Outlet Pressure_max',
'Lng_Vel_mean',
'512 Driver s Demand Engine Percent Torque_max',
'1242 Instantaneous Estimated Brake Power_min',
'245 Total Vehicle Distance_min',
'250 Engine Total Fuel Used_mean',
'velocity_kmh_max',
'Pos_Qual_min',
'IMU_Kalman_Filter_Status_min',
'905 Relative Speed Front Axle Left Wheel_mean',
'Lng_Vel_std',
'907 Relative Speed Rear Axle 1 Left Wheel_std',
'RMS_HVEL_mean',
'27 Engine Exhaust Gas Recirculation 1 Valve Position_mean',
'190 Engine Speed CAN0_mean',
'2659 Engine Exhaust Gas Recirculation 1 Mass Flow Rate_max',
'3030 Transmission Torque Converter Ratio_mean',
'4207 Message Checksum_min',
'Lat_Jerk_min',
'3357 Actual Maximum Available Engine Percent Torque_max',
'ADC_CH1_max',
'X_Accel_std',
'986 Engine Fan 1 Requested Percent Speed_mean',
'1087 Service Brake Circuit 1 Air Pressure_std',
'Long_accel_std',
'PreKF_Longitude_mean',
'190 Engine Speed_mean',
'27 Engine Exhaust Gas Recirculation 1 Valve Position_max',
'headingDegree_std',
'3226 Aftertreatment 1 Outlet NOx 1_mean',
'satellites_max',
'long_mean',
'RollRate_std',
'Pitch_imu_mean',
'907 Relative Speed Rear Axle 1 Left Wheel_min',
'4154 Actual Engine Percent Torque Fractional_mean',
'171 Ambient Air Temperature_std',
'101 Engine Crankcase Pressure 1_mean',
'X_Accel_min',
'3357 Actual Maximum Available Engine Percent Torque_min',
'250 Engine Total Fuel Used_min',
'RMS_HVEL_max',
'96 Fuel Level 1_std',
'3242 Aftertreatment 1 Diesel Particulate Filter Intake Temperature_std',
'184 Engine Instantaneous Fuel Economy_mean',
'3610 Aftertreatment 1 Diesel Particulate Filter Outlet Pressure_std',
'Exported_Elapsed_time_min',
'velocity_kmh_mean',
'Yaw_Rate_min',
'247 Engine Total Hours of Operation_mean',
'ADC_CH2_mean',
'1209 Engine Exhaust Bank 1 Pressure 1_mean',
'3251 Aftertreatment 1 Diesel Particulate Filter Differential Pressure_min',
'velocity_quality_kmh_min',
'102 Engine Intake Manifold 1 Pressure_max',
'Pos_Z_max',
'Roll_Angle_min',
'ADC_CH3_min',
'84 Wheel Based Vehicle Speed_mean',
'103 Engine Turbocharger 1 Speed_std',
'573 Transmission Torque Converter Lockup Engaged_std',
'RMS_VVEL_max',
'Head_imu2_min',
'3226 Aftertreatment 1 Outlet NOx 1_max',
'VELCov_xx_mean',
'3544 Time Remaining in Engine Operating State_std',
'satellites_mean',
'Pos_Z_mean',
'Lng_Jerk_min',
'Y_Accel_min',
'Exported_Lateral_acceleration_std',
'5313 Commanded Engine Fuel Rail Pressure_max',
'ADC_CH4_mean',
'5015 Momentary Engine Maximum Power Enable_min',
'3030 Transmission Torque Converter Ratio_std',
'523 Transmission Current Gear_mean',
'POSCov_zz_mean',
'244 Trip Distance_min',
'51 Engine Throttle Valve 1 Position 1_mean',
'POSCov_xy_max',
'POSCov_yy_std',
'RMS_HPOS_max',
'524 Transmission Selected Gear_max',
'1761 Aftertreatment 1 Diesel Exhaust Fluid Tank Volume_mean',
'2432 Engine Demand Percent Torque_std',
'PreKF_Alt_std',
'Roll_Angle_std',
'3241 Aftertreatment 1 Exhaust Temperature 1_min',
'height_max',
'POSCov_xz_min',
'5862 Aftertreatment 1 SCR Intermediate Temperature_std',
'latitude_std',
'96 Fuel Level 1_mean',
'Exported_Longitudinal_acceleration_min',
'Temp_min',
'VELCov_yy_max',
'PreKF_VertSpd_min',
'5398 Estimated Pumping Percent Torque_min',
'5015 Momentary Engine Maximum Power Enable_mean',
'524 Transmission Selected Gear_std',
'27 Engine Exhaust Gas Recirculation 1 Valve Position_min',
'3230 Aftertreatment 1 Outlet NOx 1 Reading Stable_mean',
'latitude_mean',
'PreKF_Longitude_max',
'lat_mean',
'512 Driver s Demand Engine Percent Torque_min',
'PreKF_Heading_std',
'1087 Service Brake Circuit 1 Air Pressure_min',
'1029 Trip Average Fuel Rate_mean',
'velocity_kmh_min',
'3241 Aftertreatment 1 Exhaust Temperature 1_mean',
'906 Relative Speed Front Axle Right Wheel_max',
'Roll_imu_min',
'244 Trip Distance_mean',
'244 Trip Distance_max',
'3721 Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration_max',
'3216 Engine Exhaust 1 NOx 1_max',
'4154 Actual Engine Percent Torque Fractional_min',
'POSCov_yz_min',
'3232 Aftertreatment 1 Outlet Gas Sensor 1 Heater Preliminary FMI_std',
'3216 Engine Exhaust 1 NOx 1_mean',
'gpsSpeed_min',
'Head_imu2_max',
'3231 Aftertreatment 1 Outlet Wide Range Percent Oxygen 1 Reading Stable_mean',
'2945 Active Shift Console Indicator_std',
'Roll_imu_max',
'headingDegree_mean',
'4816 Transmission Torque Converter Lockup Transition in Process_mean',
'gpsSpeed_std',
'3031 Aftertreatment 1 Diesel Exhaust Fluid Tank Temperature 1_mean',
'3031 Aftertreatment 1 Diesel Exhaust Fluid Tank Temperature 1_max',
'3031 Aftertreatment 1 Diesel Exhaust Fluid Tank Temperature 1_min',
'1761 Aftertreatment 1 Diesel Exhaust Fluid Tank Volume_std',
'1761 Aftertreatment 1 Diesel Exhaust Fluid Tank Volume_max',
'1761 Aftertreatment 1 Diesel Exhaust Fluid Tank Volume_min',
'3251 Aftertreatment 1 Diesel Particulate Filter Differential Pressure_mean',
'3251 Aftertreatment 1 Diesel Particulate Filter Differential Pressure_mean',
'3251 Aftertreatment 1 Diesel Particulate Filter Differential Pressure_std',
'5466 Aftertreatment 1 Diesel Particulate Filter Soot Load Regeneration Threshold_mean',
'5466 Aftertreatment 1 Diesel Particulate Filter Soot Load Regeneration Threshold_max',
'5466 Aftertreatment 1 Diesel Particulate Filter Soot Load Regeneration Threshold_min',
'3721 Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration_mean',
'3721 Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration_mean',
'3721 Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration_std',
'171 Ambient Air Temperature_mean',
'171 Ambient Air Temperature_max',
'185 Engine Average Fuel Economy_mean',
'185 Engine Average Fuel Economy_std',
'185 Engine Average Fuel Economy_max',
'1136 Engine ECU Temperature_mean',
'1136 Engine ECU Temperature_min',
'975 Engine Fan 1 Estimated Percent Speed_mean',
'975 Engine Fan 1 Estimated Percent Speed_std',
'975 Engine Fan 1 Estimated Percent Speed_max',
'986 Engine Fan 1 Requested Percent Speed_min',
'132 Engine Intake Air Mass Flow Rate_max',
'132 Engine Intake Air Mass Flow Rate_min',
'105 Engine Intake Manifold 1 Temperature_mean',
'1172 Engine Turbocharger 1 Compressor Intake Temperature_mean',
'2978 Estimated Engine Parasitic Losses Percent Torque_mean',
'2978 Estimated Engine Parasitic Losses Percent Torque_std',
'2978 Estimated Engine Parasitic Losses Percent Torque_min',
'245 Total Vehicle Distance_mean',
'245 Total Vehicle Distance_std',
'245 Total Vehicle Distance_max',
'177 Transmission Oil Temperature 1_std',
'244 Trip Distance_mean',
'244 Trip Distance_max',
'918 Trip Distance High Resolution_mean',
'918 Trip Distance High Resolution_std',
'918 Trip Distance High Resolution_min',

'4154 Actual Engine - Percent Torque (Fractional)_min'

'0 time_sec', '918 Trip Distance (High Resolution)_median', '244 Trip Distance_median', ' 245 Total Vehicle Distance_median', '96 Fuel Level 1_min','96 Fuel Level 1_max','96 Fuel Level 1_median',
'0                                             time_sec', '221                  245 Total Vehicle Distance_median', 'time_sec', '245 Total Vehicle Distance_median'
]

        cols_before = df.shape[1]
        df_cleaned = df.drop(columns=[col for col in columns_to_drop if col in df.columns])

        cols_after = df_cleaned.shape[1]
        dropped = cols_before - cols_after


        output_filename = filename.replace("g80.csv", "dropped_cols.csv")
        output_path = os.path.join(output_folder,output_filename)
        df_cleaned.to_csv(output_path,index=False)

        print(f" Columns before: {cols_before}")
        print(f" Columns after:  {cols_after}")
        print(f"  Columns dropped: {dropped}")


    except Exception as e:
        print(f" Failed to process {filename} due to {e}")


